config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get "example" => "home#example"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def example

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/example.haml
.row
  .col-md-12
    .jumbotron
      %h1 Mоделювання Монте Карло
      .btn-group
        = link_to "Лінійний графік", root_path, data: { no_turbolink: true }, class: "btn btn-default"
        = link_to "3D графік", example_path, data: { no_turbolink: true }, class: "btn btn-default"
    .col-md-12
      %h4
        3D модель (приклад)
      #example-chart

app/views/home/index.haml
.row
  .col-md-12
    .jumbotron
      %h1 Mоделювання Монте Карло
      .btn-group
        = link_to "Лінійний графік", root_path, data: { no_turbolink: true }, class: "btn btn-default"
        = link_to "3D графік", example_path, data: { no_turbolink: true }, class: "btn btn-default"
    .col-md-4
      %h4
        Введіть дані:
      .form
        .input-group
          %label
            Значення 1
          %input.form-control#param1{:placeholder => "Параметр 1", :type => "number"}
        %hr
        .input-group
          %label
            Значення 2
          %input.form-control#param2{:placeholder => "Параметр 2", :type => "number"}
        %hr
        .input-group
          %label
            Значення 3
          %input.form-control#param3{:placeholder => "Параметр 3", :type => "number"}
        %br
        %button.btn.btn-primary#calc{:type => "button"}
          Розрахувати
    .col-md-8
      %h4
        Лінійний графік
      #line-chart

app/views/layouts/application.haml
!!!
%html
  %head
    %title MonteCarloSimulation
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %script{:src => "http://x3dom.org/x3dom/dist/x3dom-full.js", :type => "text/javascript"}
    %link{:href => "http://www.x3dom.org/download/dev/x3dom.css", :rel => "stylesheet", :type => "text/css"}
  %body
    = yield